import employeePage from "../../PageObjects/AdministrationPages/employeePage"
const employeeObject = new employeePage()
var randomNumber = Math.floor(Math.random() * 10000);
Cypress.Commands.add("fieldValidationEmployeeData",()=>{
    cy.waitForGenericLoader()
    // cy.get(employeeObject.clickAdministrationMenu).click({force:true})
    // cy.waitForGenericLoader()
    // cy.wait(5000)
    cy.companySelect()
    cy.xpath(employeeObject.clickEmployeeTab).click({force:true})
    cy.waitForGenericLoader()
    cy.xpath(employeeObject.clickAddNewEmployeeBtn).should('be.visible').click({force:true})
    cy.get('[class="dx-overlay-content dx-popup-normal dx-popup-draggable dx-resizable dx-popup-flex-height"]').should('be.visible')
    cy.get(employeeObject.saveAndClose).click({force:true})
    cy.get('[class="dx-show-invalid-badge dx-textbox dx-texteditor dx-editor-outlined dx-texteditor-empty dx-widget dx-validator dx-visibility-change-handler dx-invalid"').should('be.visible')
})
Cypress.Commands.add('saveEmployee',()=>{
    cy.get(employeeObject.firstName).type('peter ' + randomNumber)
    cy.get(employeeObject.middleName).type('m')
    cy.get(employeeObject.lastName).type('serge')
    cy.get(employeeObject.emailInput).type('johndoe123@gmail.com')
    cy.xpath(employeeObject.primaryPhone).type('8940545447')
    cy.xpath(employeeObject.secondryPhone).type('9234354545')
    cy.xpath(employeeObject.clickDob).click({force:true})
    cy.get('.dx-calendar-cell.dx-calendar-today').click({force:true})
    cy.xpath(employeeObject.clickGender).click({force:true})
    cy.xpath('//div[@class="dx-item-content dx-list-item-content" and text()="Male"]').click({force:true})
    // cy.xpath(employeeObject.clickMaritalStatus).click({force:true})
    // cy.xpath('//div[@class="dx-item-content dx-list-item-content" and text()="Single"]').click({force:true})
    cy.xpath(employeeObject.ssnInput).type('454646649')
    cy.get(employeeObject.primaryAddressInput).type('street no 2, london')
    cy.get(employeeObject.cityInput).type('london')
    cy.get(employeeObject.zipInput).type('43533')
    cy.xpath(employeeObject.clickState).click({force:true})
    cy.xpath('//div[@class="dx-item-content dx-list-item-content" and text()="Arizona"]').click({force:true})
    cy.xpath(employeeObject.clickEmployeeType).click({force:true})
    cy.xpath(employeeObject.selectEmployeeType).click({force:true})
    cy.xpath(employeeObject.clickRole).click({force:true})
    cy.xpath(employeeObject.selectRole).click({force:true})
    cy.get('[name="password"]').type('Employee@Password')
    cy.get('[name="passwordCopy"]').type('Employee@Password')
    cy.get(employeeObject.saveAndClose).click({force:true})

})
Cypress.Commands.add('editEmployee',()=>{
    cy.waitForGenericLoader()
    cy.xpath(employeeObject.clickEmployeeTab).click({force:true})
    cy.waitForGenericLoader()
    cy.get(employeeObject.gridSearch).clear().type('serge')
    cy.waitForGenericLoader()
    cy.wait(2000)
    cy.get(employeeObject.btnEdit).eq(0).click({force:true})
    cy.get(employeeObject.firstName).should('be.visible').clear().type('doom ' + randomNumber)
    cy.get(employeeObject.saveAndClose).click({force:true})
})

Cypress.Commands.add('deleteEmployee',()=>{
    cy.waitForGenericLoader()
    cy.get(employeeObject.gridSearch).clear().type('serge')
    cy.waitForGenericLoader()
    cy.wait(2000)
    cy.get(employeeObject.btnDelete).eq(0).click({force:true})
    cy.xpath(employeeObject.confirmationPopup).should('be.visible')
    cy.get(employeeObject.btnYes).click({force:true})
    cy.waitForGenericLoader()
})