import TemplatePage from "../../PageObjects/AdministrationPages/TemplatePage";
const templateObject = new TemplatePage()
var randomNumber = Math.floor(Math.random() * 10000);

Cypress.Commands.add("fieldValidationPhrases",()=>{
    cy.waitForGenericLoader()
    cy.xpath(templateObject.clickTemplateTab).click({force:true})
    cy.waitForGenericLoader()
    cy.xpath(templateObject.clickPhrasesTab).click({force:true})
    cy.xpath(templateObject.clickNewPhrasesBtn).should('be.visible').click({force:true})
    // cy.get('[class="dx-overlay-content dx-popup-normal dx-resizable dx-popup-flex-height"]').should('be.visible')
    cy.xpath('//button[@class="btn btn-md btn-outline-secondary" and text()=" Save "]').click({force:true})
    cy.get('[class="dx-overlay dx-invalid-message-bottom dx-widget dx-visibility-change-handler dx-invalid-message"]').should('be.visible')})
Cypress.Commands.add("savePhrases",()=>{
    // cy.task("getCache", "randomNumber").then((a: any) => {
        cy.wait(2000)
        cy.get(templateObject.titleInput).type('Automated Phrases' + randomNumber)
        cy.xpath('//button[@class="btn btn-md btn-outline-secondary" and text()=" Save "]').click({force:true})
        cy.saveToast()
        cy.intercept('api/template-type/dx/grid*').as('getGridList')
        cy.get(templateObject.closeBtn).click({force:true})
        cy.wait('@getGridList')
    // })
})

Cypress.Commands.add('editSavePhrases',()=>{
    cy.waitForGenericLoader()
    cy.xpath(templateObject.clickTemplateTab).click({force:true})
    cy.waitForGenericLoader()
    cy.xpath(templateObject.clickPhrasesTab).click({force:true})
    cy.get(templateObject.gridSearch).clear().type('Automated Phrases')
    cy.waitForGenericLoader()
    cy.wait(3000)
    cy.get(templateObject.btnEdit).eq(0).click({force:true})
    // cy.get(templateObject.addPopupVisible).should('be.visible')
    cy.get(templateObject.titleInput).clear().type('Edit Automated Phrases '+ randomNumber)
    cy.xpath('//button[@class="btn btn-md btn-outline-secondary" and text()=" Save "]').click({force:true})
})
Cypress.Commands.add('deletePhrases',()=>{
    cy.waitForGenericLoader()
    cy.xpath(templateObject.clickTemplateTab).click({force:true})
    cy.waitForGenericLoader()
    cy.xpath(templateObject.clickPhrasesTab).click({force:true})
    cy.get(templateObject.gridSearch).clear().type('Automated Phrases')
    cy.waitForGenericLoader()
    cy.wait(3000)
    cy.get(templateObject.btnDelete).eq(0).click({force:true})
    cy.xpath(templateObject.confirmationPopup).should('be.visible')
    cy.get(templateObject.btnYes).click({force:true})
    cy.waitForGenericLoader()
})