import TemplatePage from "../../PageObjects/AdministrationPages/TemplatePage";
const templateObject = new TemplatePage()
var randomNumber = Math.floor(Math.random() * 10000);

Cypress.Commands.add("fieldValidationSelectableList",()=>{
    cy.waitForGenericLoader()
    cy.xpath(templateObject.clickTemplateTab).click({force:true})
    cy.waitForGenericLoader()
    cy.xpath(templateObject.clickSelectableListTab).click({force:true})
    cy.xpath(templateObject.clickNewBtnList).should('be.visible').click({force:true})
    // cy.get('[class="dx-overlay-content dx-popup-normal dx-resizable dx-popup-flex-height"]').should('be.visible')
    cy.xpath('//button[@class="btn btn-md btn-outline-secondary" and text()=" Save "]').click({force:true})
    cy.xpath('//div[@class="dx-overlay-content dx-invalid-message-content" and text()="Title is required"]').should('be.visible')})
Cypress.Commands.add("saveSelectableList",()=>{
    // cy.task("getCache", "randomNumber").then((a: any) => {
        cy.wait(2000)
        cy.get(templateObject.titleInput).type('Automated Template List ' + randomNumber)
        cy.xpath(templateObject.clickCategroyList).click({force:true})
        cy.xpath('//div[@class="dx-item-content dx-list-item-content" and contains(text(), "Automated Category")]').eq(0).click({force:true})
        cy.get('[title="Add a row"]').click({force:true})
        cy.xpath('//tr[@class="dx-row dx-data-row dx-row-lines dx-row-inserted dx-edit-row"]//input[@type="text"]')
        .eq(0).type('normal range')
        cy.get('[class="dx-widget dx-checkbox dx-datagrid-checkbox-size"]').eq(0).click({force:true})
        cy.xpath('//a[@class="dx-link dx-link-save" and text()="Save"]').click({force:true}).wait(1000)
        cy.xpath('//button[@class="btn btn-md btn-outline-secondary" and text()=" Save "]').click({force:true})
        // cy.saveToast()
        cy.intercept('api/selectable-lists/dx/grid*').as('getGridList')
        cy.get(templateObject.closeBtn).click({force:true})
        cy.wait('@getGridList')
    // })
})

Cypress.Commands.add('editSaveSelectableList',()=>{
    cy.waitForGenericLoader()
    cy.xpath(templateObject.clickTemplateTab).click({force:true})
    cy.waitForGenericLoader()
    cy.xpath(templateObject.clickSelectableListTab).click({force:true})
    cy.get(templateObject.gridSearch).clear().type('Automated Template List')
    cy.waitForGenericLoader()
    cy.wait(3000)
    cy.get(templateObject.btnEdit).eq(0).click({force:true})
    // cy.get(templateObject.addPopupVisible).should('be.visible')
    cy.get(templateObject.titleInput).clear().type('Edit Automated Template List '+ randomNumber)
    cy.xpath('//button[@class="btn btn-md btn-outline-secondary" and text()=" Save "]').click({force:true})
})
Cypress.Commands.add('deleteSelectableList',()=>{
    cy.waitForGenericLoader()
    cy.xpath(templateObject.clickTemplateTab).click({force:true})
    cy.waitForGenericLoader()
    cy.xpath(templateObject.clickSelectableListTab).click({force:true})
    cy.get(templateObject.gridSearch).clear().type('Automated Category')
    cy.waitForGenericLoader()
    cy.get(templateObject.btnDelete).eq(0).click({force:true})
    cy.xpath(templateObject.confirmationPopup).should('be.visible')
    cy.get(templateObject.btnYes).click({force:true})
    cy.waitForGenericLoader()
})