import companiesPage from "../PageObjects/companiesPage";
const companyObject =new companiesPage()


Cypress.Commands.add("fieldValidationCompaniesData",()=>{
    cy.waitForGenericLoader()
    cy.get(companyObject.clickMenuCompanies).click({force:true})
    cy.xpath(companyObject.clickAddNewCompanyBtn).should('be.visible').click({force:true})
    cy.get('[class="dx-overlay-content dx-popup-normal dx-popup-draggable dx-resizable"]').should('be.visible')
    cy.get(companyObject.saveAndClose).click({force:true})
    cy.get('[class="dx-show-invalid-badge dx-textbox dx-texteditor dx-editor-outlined dx-texteditor-empty dx-widget dx-validator dx-visibility-change-handler dx-invalid"').should('be.visible')
})
Cypress.Commands.add('saveCompanies',()=>{
    cy.get(companyObject.nameInput).type('itbytes')
    cy.xpath(companyObject.phoneInput).eq(0).type('8940545447')
    cy.get(companyObject.primaryAddressInput).type('street no 2, london')
    cy.get(companyObject.cityInput).type('london')
    cy.get(companyObject.zipInput).type('43533')
    cy.xpath('//input[@name="fax"]//parent::div//input[@type="text"]').type('3424342088')
    cy.xpath(companyObject.clickState).click({force:true})
    cy.xpath('//div[@class="dx-item-content dx-list-item-content" and text()="Texas"]').click({force:true})
    cy.xpath('//span[@class="dx-field-item-label-text" and text()="Service Type"]').click({force:true})
    cy.contains('div', 'Private Practice').click({force:true})
    cy.get('[name="firstname"]').type('awais')
    cy.get('[name="lastname"]').type('admin')
    cy.get('[name="userid"]').type('awais123')
    cy.get('[name="password"]').type('Pass@007')
    cy.get('[name="confirmpassword"]').type('Pass@007')
    cy.get('[name="email"]').type('awaisadmin123@getnada.com')
    cy.xpath(companyObject.phoneInput).eq(1).type('564054493')
    cy.get(companyObject.saveAndClose).click({force:true})
})
Cypress.Commands.add('editCompanies',()=>{
    cy.get(companyObject.clickMenuCompanies).click({force:true})
    cy.waitForGenericLoader()
    cy.get(companyObject.gridSearch).clear().type('itbytes{enter}')
    cy.waitForGenericLoader()
    cy.wait(2000)
    cy.get(companyObject.btnEdit).eq(0).click({force:true})
    cy.get('[class="dx-overlay-content dx-popup-normal dx-popup-draggable dx-resizable"]').should('be.visible')
    cy.get(companyObject.nameInput).clear().type('IT BYTES')
    cy.get(companyObject.saveAndClose).click({force:true})
})

Cypress.Commands.add('deleteCompanies',()=>{
    // cy.get(companyObject.gridSearch).clear().type('serge')
    cy.waitForGenericLoader()
    cy.get(companyObject.btnDelete).eq(0).click({force:true})
    cy.xpath(companyObject.confirmationPopup).should('be.visible')
    cy.get(companyObject.btnYes).click({force:true})
    cy.waitForGenericLoader()
})