import patientPage from "../PageObjects/PatientsPages/patientPage"
const patientObject = new patientPage()
Cypress.Commands.add("fieldValidationPatientData",()=>{
    cy.waitForGenericLoader()
    cy.xpath(patientObject.clickAddNewPatientBtn).should('be.visible').click({force:true})
    cy.get('[class="dx-overlay-content dx-popup-normal dx-popup-draggable dx-resizable"]').should('be.visible')
    cy.get(patientObject.saveAndClose).click({force:true})
    cy.xpath(patientObject.nameIsRequired).should('be.visible')
})
Cypress.Commands.add('savePatients',()=>{
    cy.xpath(patientObject.clickAddNewPatientBtn).click({force:true})
    cy.get('[class="dx-overlay-content dx-popup-normal dx-popup-draggable dx-resizable"]').should('be.visible')
    cy.get(patientObject.firstName).type('john')
    cy.get(patientObject.middleName).type('m')
    cy.get(patientObject.lastName).type('doe')
    cy.xpath(patientObject.clickCommunicationMethod).click({force:true})
    cy.xpath('//div[@class="dx-item-content dx-list-item-content" and text()="SMS Text"]').click({force:true})
    cy.xpath(patientObject.clickCommunicationMethod).click({force:true})
    cy.xpath('//div[@class="dx-item-content dx-list-item-content" and text()="Email"]').click({force:true})
    cy.get(patientObject.emailInput).type('johndoe123@gmail.com')
    cy.xpath(patientObject.primaryPhone).type('8940545447')
    cy.xpath(patientObject.secondryPhone).type('9234354545')
    cy.xpath(patientObject.clickDob).click({force:true})
    cy.get('.dx-calendar-cell.dx-calendar-today').click({force:true})
    cy.xpath(patientObject.clickGender).click({force:true})
    cy.xpath('//div[@class="dx-item-content dx-list-item-content" and text()="Male"]').click({force:true})
    cy.xpath(patientObject.clickMaritalStatus).click({force:true})
    cy.xpath('//div[@class="dx-item-content dx-list-item-content" and text()="Single"]').click({force:true})
    cy.get(patientObject.ssnInput).type('454646649')
    cy.get(patientObject.primaryAddressInput).type('street no 2, london')
    cy.get(patientObject.cityInput).type('london')
    cy.get(patientObject.zipInput).type('43533')
    cy.xpath(patientObject.clickState).click({force:true})
    cy.xpath('//div[@class="dx-item-content dx-list-item-content" and text()="arizona"]').click({force:true})
    cy.get(patientObject.saveAndClose).click({force:true})

})
Cypress.Commands.add('editPatient',()=>{
    cy.waitForGenericLoader()
    cy.get(patientObject.gridSearch).clear().type('doe')
    cy.waitForGenericLoader()
    cy.get(patientObject.btnEdit).eq(0).click({force:true})
    cy.get(patientObject.addPopupVisible).should('be.visible')
    cy.get(patientObject.firstName).clear().type('peter')
    cy.get(patientObject.saveAndClose).click({force:true})
})

Cypress.Commands.add('deletePatient',()=>{
    cy.get(patientObject.gridSearch).clear().type('doe')
    cy.waitForGenericLoader()
    cy.get(patientObject.btnDelete).eq(0).click({force:true})
    cy.xpath(patientObject.confirmationPopup).should('be.visible')
    cy.get(patientObject.btnYes).click({force:true})
    cy.waitForGenericLoader()
})